name: New Release Workflow

on:
  
  release:
    types: [ released ]

jobs:

  publish_prod_packages:

    name: Publish Snapshot Packages
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Update to snapshot version
        env:
          VERSION: ${{ github.ref_name }}
        run: |
            echo "Updating to version: ${VERSION}"
            mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${VERSION}
            mvn versions:set-property -Dproperty=assimbly.version -DnewVersion=${VERSION}

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_snapshot_packages:

    name: Publish Snapshot Packages
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'develop'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Update to snapshot version
        env:
          SNAPSHOT_VERSION: ${{ github.ref_name }}-SNAPSHOT
        run: |
            echo "Updating to version: ${SNAPSHOT_VERSION}"
            mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${SNAPSHOT_VERSION}
            mvn versions:set-property -Dproperty=assimbly.version -DnewVersion=${SNAPSHOT_VERSION}

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


