name: Publish Snapshots

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'snapshots-tests'

jobs:
  delete_older_snapshots:

    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:

      - name: Delete older snapshots
        uses: smartsquaregmbh/delete-old-packages@v0.7.0
        with:
          organization: assimbly
          type: maven
          keep: 0
          version-pattern: "^\\S+\\-SNAPSHOT$"
          names: |
            org.assimbly.runtime
            org.assimbly.integration-rest
            org.assimbly.integration
            org.assimbly.dil
            org.assimbly.broker-rest
            org.assimbly.broker

  publish_runtime_snapshot:
    needs: [delete_older_snapshots]

    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    env:
      GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          ref: "develop"
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          
          repositories: >
              [
                  {
                      "id": "maven",
                      "name": "Maven Central",
                      "url": "https://repo1.maven.org/maven2"
                  },
                  {
                    "id": "github",
                    "name": "Assimbly Base Repository",
                    "url": "https://maven.pkg.github.com/assimbly/base",
                    "snapshots": {
                      "enabled": "true"
                    }
                  },
                  {
                    "id": "github",
                    "name": "Assimbly Runtime Repository",
                    "url": "https://maven.pkg.github.com/assimbly/runtime",
                    "snapshots": {
                      "enabled": "true"
                    }
                  },
                  {
                    "id": "github",
                    "name": "Assimbly Custom-Components Repository",
                    "url": "https://maven.pkg.github.com/assimbly/custom-components",
                    "snapshots": {
                      "enabled": "true"
                    }
                  },
                  {
                      "id": "aurea",
                      "name": "Aurea Sonic Repository",
                      "url": "https://int-factory.aurea.com/nexus/content/repositories/sonic-releases/"
                  }
              ]

          servers: >
              [
                  {
                      "id": "github",
                      "username": "$GITHUB_ACTOR",
                      "password": "$GITHUB_TOKEN"
                  }
              ]
      
      - name: Remove HTTP blocker from the built in settings.xml
        run: |
          export MAVEN_PATH=$(mvn -X | grep "home" | head -1 | cut -d " " -f 3)
          echo "this is the path: $MAVEN_PATH"
          echo '<?xml version="1.0" encoding="UTF-8"?>' > "$MAVEN_PATH/conf/settings.xml"
          echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.2.0" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.2.0 https://maven.apache.org/xsd/settings-1.2.0.xsd">' >> "$MAVEN_PATH/conf/settings.xml"
          echo '</settings>' >> "$MAVEN_PATH/conf/settings.xml"
          cat $MAVEN_PATH/conf/settings.xml

      - name: Update POM Version
        env:
          VERSION: 4.0.0-SNAPSHOT
        run: |
            echo "Updating to version: ${VERSION}"
            mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${VERSION}
            mvn versions:set-property -Dproperty=assimbly.version -DnewVersion=${VERSION}

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}